# Generated by Django 5.2 on 2025-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acompanamiento_imagen_acompanamiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='producto',
        ),
        migrations.AddField(
            model_name='comanda',
            name='detalle',
            field=models.TextField(default='Sin detalle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comanda',
            name='hora_fin_comanda',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
