# Generated by Django 5.2 on 2025-07-04 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_comanda_producto_comanda_detalle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleComanda',
            fields=[
                ('id_detalle_comanda', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_detalle_comanda', models.PositiveIntegerField(default=1)),
                ('acompanamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.acompanamiento')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comanda')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.producto')),
            ],
        ),
    ]
