# Generated by Django 5.2 on 2025-07-04 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_detallecomanda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comanda',
            name='detalle',
        ),
    ]
